{% set name = "pandexo.engine" %}
{% set version = "1.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7199c175117e5170da13d3f613b804b93da41853dedcc3c9cbf4a62feaec68d4" %}

package:
  name: '{{ name|lower }}'
  version: {{ environ['VERSION'] }}

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script_env:
   - VERSION
   - CONDA_BLD_PATH
  entry_points:
    - start_pandexo=pandexo.engine.run_online:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy 
    - bokeh
    - tornado
    - pandas
    - joblib
    - photutils
    - astropy
    - pysynphot
    - sqlalchemy
    - sphinx 
  run:
    - python
    - numpy 
    - bokeh 
    - tornado
    - pandas
    - joblib
    - photutils
    - astropy 
    - pysynphot
    - sqlalchemy
    - sphinx 

test:
  imports:
    - pandexo
    - pandexo.engine
    - pandexo.engine.reference
    - pandexo.engine.static
    - pandexo.engine.static.css
    - pandexo.engine.static.fonts
    - pandexo.engine.static.img
    - pandexo.engine.static.js
    - pandexo.engine.temp
    - pandexo.engine.templates
    - pandexo.engine.utils

about:
  home: https://github.com/natashabatalha/PandExo
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: Summary of the package
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''